/* import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Morkaz!</a>
        </h1>
      </main>

    </div>
  )
} */

import Head from 'next/head'
import dynamic from 'next/dynamic'
import Nav from '../components/nav'
import Slider from '../components/slider'
import Alumni from '../components/alumni'
import Conferences from '../components/conferences'
import About from '../components/about'
import Footer from '../components/Footer'

import tog from '../components/toggle'


/* const DynamicComponentWithNoSSR = dynamic(
  () => import('../components/toggle'),
  { ssr: false } // <-- not including this component on server-side
) */

export default function Home() {
  return (
    <>
      <Head>
        <title>Morkaz Agege</title>
        <meta httpEquiv="content-language" content="en" />
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="theme-color" content="#4299e1" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"
        />
      </Head>
      <div>
        <Nav />
        <Slider />
          <div className="container mx-auto">
            <Alumni />
            <Conferences />
            <About />
            <Footer />
          </div>
      </div>
    </>
  )
}

